#pragma once

#include "CkJolt/Body/CkJoltBody_Utils.h"
#include "CkRuntimeMesh/CkRuntimeMesh_Utils.h"
#include "CkRuntimeMesh/Display/CkRuntimeMeshDisplay_Utils.h"

#include <UObject/Object.h>

#include "CkTest_RuntimeMeshBpHarness.generated.h"

// --------------------------------------------------------------------------------------------------------------------

// Native parent of a transient Blueprint: the events are implemented by compiled BP graphs, so every call into the
// RuntimeMesh/Display/JoltBody surface below runs through generated bytecode rather than a native utility call.
UCLASS(Blueprintable)
class UCk_Test_RuntimeMeshBpHarness_UE : public UObject
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintImplementableEvent)
    void
    DispatchSlice(
        UPARAM(ref) FCk_Handle_RuntimeMesh& InSource,
        const FCk_Request_RuntimeMesh_Slice& InRequest);

    UFUNCTION(BlueprintImplementableEvent)
    void
    ComposeResult(
        UPARAM(ref) FCk_Handle_Transform& InDisplayOwner,
        UPARAM(ref) FCk_Handle& InEntity,
        const FCk_RuntimeMeshDisplay_Spec& InDisplay,
        const FCk_JoltBody_Spec& InBody);

    UFUNCTION(BlueprintImplementableEvent)
    void
    InspectComposition(
        const FCk_Handle_RuntimeMeshDisplay& InDisplay,
        const FCk_Handle_JoltBody& InBody);

    UFUNCTION(BlueprintCallable)
    void
    OnSliceResolved(
        FCk_RuntimeMesh_SliceResult InResult);

    UFUNCTION(BlueprintCallable)
    void
    OnRequestCompleted(
        FCk_Handle InRequestOwner,
        ECk_Request_OperationResult InResult);

    UFUNCTION(BlueprintCallable)
    void
    OnJoltResolved(
        FCk_Handle_JoltBody InBody,
        ECk_JoltBody_SetupState InState,
        ECk_JoltBody_SetupFailure InFailure);

    UFUNCTION(BlueprintCallable)
    void
    CaptureComposition(
        ECk_RuntimeMesh_SetupState InDisplayState,
        ECk_RuntimeMeshDisplay_SetupFailure InDisplayFailure,
        ECk_JoltBody_SetupState InBodyState,
        ECk_JoltBody_SetupFailure InBodyFailure,
        const FString& InDiagnostic);

public:
    UPROPERTY()
    TArray<FCk_RuntimeMesh_SliceResult> Results;

    UPROPERTY()
    TArray<ECk_Request_OperationResult> Completions;

    UPROPERTY()
    int32 JoltCallbacks = 0;

    UPROPERTY()
    ECk_JoltBody_SetupState JoltCallbackState = ECk_JoltBody_SetupState::Pending;

    UPROPERTY()
    ECk_JoltBody_SetupFailure JoltCallbackFailure = ECk_JoltBody_SetupFailure::None;

    UPROPERTY()
    bool CompositionObserved = false;

    UPROPERTY()
    ECk_RuntimeMesh_SetupState DisplayState = ECk_RuntimeMesh_SetupState::Pending;

    UPROPERTY()
    ECk_RuntimeMeshDisplay_SetupFailure DisplayFailure = ECk_RuntimeMeshDisplay_SetupFailure::None;

    UPROPERTY()
    ECk_JoltBody_SetupState BodyState = ECk_JoltBody_SetupState::Pending;

    UPROPERTY()
    ECk_JoltBody_SetupFailure BodyFailure = ECk_JoltBody_SetupFailure::None;

    UPROPERTY()
    FString Diagnostic;
};

// --------------------------------------------------------------------------------------------------------------------
